### ISSUE TITLE
Template parsing requires `ignorecase`

### ISSUE THREAD

**Issue by ebothmann** [lifepillar/vim-colortemplate#1]
The field name search strings are lowercase, whereas the field names in the templates start with an upper-case character. Therefore, template parsing fails when `ignorecase` is not set.

**Comment by lifepillar** [comment]
Good catch! I'll fix that ASAP.

**Comment by ebothmann** [comment]
No prob, thx for the template, seems to work like a charm otherwise!

**Comment by lifepillar** [comment]
Thanks. Keep in mind that the plugin is not stable yet. Time permitting, I plan to add a couple of major new features, and I might possibly break something on the way. But yes, it should already be fully functional.
