### ISSUE TITLE
Possible to include any code block before anything else?

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-colortemplate#10]
I put dark and light variants in different files, normally I'd do:

this in the dark variant:
```vim
if &background == 'light'
  exe "so ".fnamemodify(expand('<sfile>:p'), ":h")."/vsdark.vim"
  finish
endif
```

and this in the light variant:
```vim
if &background == 'dark'
  exe "so ".fnamemodify(expand('<sfile>:p'), ":h")."/vsdark.vim"
  finish
endif
```

In the colortemplate I have this just after the header:

```
Include: _vscommon

#===================================================================
# Dark variant
#===================================================================

Background: dark
```

with _vscommon:
```
# vim: ft=colortemplate
verbatim
if &background == 'light' && expand('<sfile>:t') == "vsdark.vim"
  exe "so ".fnamemodify(expand('<sfile>:p'), ":h")."/vslight.vim"
  finish
elseif &background == 'dark' && expand('<sfile>:t') == "vslight.vim"
  exe "so ".fnamemodify(expand('<sfile>:p'), ":h")."/vsdark.vim"
  finish
endif
call vsd#init()
let s:load_for = { ft -> g:VSD[ft] || g:VSD.extra_syntax }
endverbatim
```

But what I get in the colorscheme is:
```vim
if !(has('termguicolors') && &termguicolors) && !has('gui_running')
      \ && (!exists('&t_Co') || &t_Co < 256)
  echoerr '[Vim Studio Dark] There are not enough colors.'
  finish
endif

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'vsdark'

if &background == 'light' && expand('<sfile>:t') == "vsdark.vim"
  exe "so ".fnamemodify(expand('<sfile>:p'), ":h")."/vslight.vim"
  finish
elseif &background == 'dark' && expand('<sfile>:t') == "vslight.vim"
  exe "so ".fnamemodify(expand('<sfile>:p'), ":h")."/vsdark.vim"
  finish
endif
call vsd#init()
let s:load_for = { ft -> g:VSD[ft] || g:VSD.extra_syntax }
```

That is, my block is put after `background` is set, and it can't run. And since it could terminate the script, I'd want it really before anything else.

This is done with `Include`, but with `verbatim` (it would have been easier and I tried it first) it's the same.

Could that `verbatim` block be run before all the rest? Thanks

**Comment by lifepillar** [comment]
One way is hacking it as follows:

```vim
Include: _vscommon

Background: dark

# Put your dark theme definitions here

Background: light
Color: x rgb(0,0,0) ~
Normal x x
# eof
```

Or, possibly better:

```
Background: dark

verbatim
if expand('<sfile>:t') == "vslight.vim"
  exe "so ".fnamemodify(expand('<sfile>:p'), ":h")."/vslight.vim"
  finish
endif
endverbatim

Color: x rgb(0,0,0) ~
Normal x x

Background: light

# Definitions for light theme go her
```

Then, exchange `dark` and `light` for the light template.

Colortemplate intentionally makes stuff like what you are trying to do difficult to achieve, because not idiomatic. Why would you load a dark colorscheme when the user explicitly asks for a light colorscheme (or vice versa?)? That's not how colorschemes are expected to work. See `$VIMRUNTIME/share/vim/vim81/colors/README.txt` and `:help colortemplate-best-practices`.

If you want a colorscheme that adapts to the background, you should generate a single file instead, without any additional control code (you may still keep two separate templates):

```
Background: dark
Include: dark-variant.colortemplate
Background: light
Include: light-variant.colortemplate
```

This way, the user may choose the desired variant of your colorscheme just by setting `background` accordingly.

**Comment by mg979** [comment]
Ok thanks. The only reason I wanted this for, is because when I update a color scheme, it takes a long time to generate the scheme, if it must update both variants, so I generally make changes in the dark variant and then maybe I port them to the light variant, that stays in a different file.

Since it's just a 4 lines snippet, right now I'm adding it manually after theme generation, it's working ok. I was just wondering if there was a default way of doing this. Thanks.

> Why would you load a dark colorscheme when the user explicitly asks for a light colorscheme (or vice versa?)?

That's what actually happens with that block. In my example I have `vsdark` and `vslight`:
* current bg: dark, current scheme: vsdark
* set bg=light
* vsdark is reloaded, the block evaluates true so it terminates and the light variant is sourced instead.
* the reverse happens when vslight is loaded and you do `set bg=dark`

**Comment by lifepillar** [comment]
Re performance: computing color approximations and stats is a significant hit. You may get a speedup if you hard code 256-based color values instead of letting Colortemplate compute them.

**Comment by mg979** [comment]
Ok thanks. I prefer to leave it like that for now, maybe I'll turn stats off.
