### ISSUE TITLE
Windows paths problem

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-colortemplate#11]
![Imgur](https://i.imgur.com/cN6pmdR.png) 

I could fix it by replacing [this line](https://github.com/lifepillar/vim-colortemplate/blob/d9b2cc7643d900fb577fb0be0cfc5608e78633d7/autoload/colortemplate.vim#L62) with:
```vim
if match(substitute(l:path, '\', '/', 'g'), '^' . substitute(l:dir, '\', '/', 'g')) == -1
```

The `match` function doesn't seem to like backslashes much, this:
```
match('C:\abc', '^C:\abc')
```
returns -1 and this as well:
```
match('C:\\abc', '^C:\\abc')
```
so escaping it doesn't help.

**Comment by mg979** [comment]
Apparently vim-fugitive is using the same trick as well:

https://github.com/tpope/vim-fugitive/commit/e9dc3637458616ea9f1a112652dd4b4678f251f9

using `tr()` instead of `substitute()`

**Comment by lifepillar** [comment]
Thanks for reporting this and for suggesting a workaround. The current master should fix it, but I haven't tested in under Windows.

**Comment by mg979** [comment]
You forgot an ampersand (should be [`!&shellslash`](https://github.com/lifepillar/vim-colortemplate/blob/cd19a09051c3679237798b20e9ef6f0b79b20657/autoload/colortemplate.vim#L48)) and it throws an error, otherwise it works (after fixing it). Thanks!

**Comment by lifepillar** [comment]
Good catch, fixed!
