### ISSUE TITLE
Getting around a vim bug

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-colortemplate#13]
The vim version I generally use (vim 8.0, debian stable) has this bug:

https://www.reddit.com/r/vim/comments/22krs1/using_set_backgrounddark_in_vim_resets_the/
https://groups.google.com/forum/#!msg/vim_dev/afPqwAFNdrU/nqh6tOM87QUJ

Basically, setting `ctermbg` to a value != 0 makes the `&background` light.

Possible workarounds:

1. simplest fix seems [this](https://github.com/tomasr/molokai/pull/26#issue-10578678) (putting `set bg` at the end of the scheme)

2. to split groups in blocks like:
```
if &termguicolors || has('gui_running') || has('nvim')
  hi Normal guifg=#c5d4dd guibg=#1e1e1e guisp=NONE cterm=NONE gui=NONE
  hi MatchParen guifg=#ff0000 guibg=NONE guisp=NONE cterm=NONE gui=NONE
else
  hi Normal ctermfg=252 ctermbg=0 cterm=NONE
  hi MatchParen ctermfg=196 ctermbg=NONE cterm=NONE
endif
```

Note that I include `cterm=` in the first section because terminal vim (not neovim or newer vim versions) even tends to mix settings when using termguicolors.

It would also speed up colorscheme loading, but n.1 seems much easier.

**Comment by lifepillar** [comment]
Which Vim version exactly has that issue (so I can test it)?

Are you sure that setting `bg` at the end of a colorscheme doesn't have any unintended consequences?

As for 2, you can implement it in your template with `verbatim` blocks. Sure, if the issue were dealt with by Colortemplate it would be better.

**Comment by mg979** [comment]
Vim version is:
```
:version                                                                                                                                                                                               
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)                                                                                                                                     
Patch incluse: 1-197, 322, 377-378, 550, 703, 706-707                                                                                                                                                  
Modificato da pkg-vim-maintainers@lists.alioth.debian.org                                                                                                                                              
Compilato da pkg-vim-maintainers@lists.alioth.debian.org                                                                                                                                               
Versione gigante con GUI GTK2.  Funzionalità incluse (+) o escluse (-):                                                                                                                                
+acl             +cmdline_compl   +digraphs        +folding         +langmap         +mouseshape      -mzscheme        +python3         +syntax          +toolbar         +writebackup                 
+arabic          +cmdline_hist    +dnd             -footer          +libcall         +mouse_dec       +netbeans_intg   +quickfix        +tag_binary      +user_commands   +X11                         
+autocmd         +cmdline_info    -ebcdic          +fork()          +linebreak       +mouse_gpm       +num64           +reltime         +tag_old_static  +vertsplit       -xfontset                    
+balloon_eval    +comments        +emacs_tags      +gettext         +lispindent      -mouse_jsbterm   +packages        +rightleft       -tag_any_white   +virtualedit     +xim                         
+browse          +conceal         +eval            -hangul_input    +listcmds        +mouse_netterm   +path_extra      +ruby            +tcl             +visual          +xpm                         
++builtin_terms  +cryptv          +ex_extra        +iconv           +localmap        +mouse_sgr       +perl            +scrollbind      +termguicolors   +visualextra     +xsmp_interact               
+byte_offset     +cscope          +extra_search    +insert_expand   +lua             -mouse_sysmouse  +persistent_undo +signs           +terminfo        +viminfo         +xterm_clipboard             
+channel         +cursorbind      +farsi           +job             +menu            +mouse_urxvt     +postscript      +smartindent     +termresponse    +vreplace        -xterm_save                  
+cindent         +cursorshape     +file_in_path    +jumplist        +mksession       +mouse_xterm     +printer         +startuptime     +textobjects     +wildignore                                   
+clientserver    +dialog_con_gui  +find_in_path    +keymap          +modify_fname    +multi_byte      +profile         +statusline      +timers          +wildmenu                                     
+clipboard       +diff            +float           +lambda          +mouse           +multi_lang      -python          -sun_workshop    +title           +windows 
```
I think any vim version older than that should behave the same,

For now I use this, as it seems `&background` is 'recalibrated' by setting the Normal highlight group:
```
hi Normal ctermfg=252 ctermbg=234 guifg=#c5d4dd guibg=#1e1e1e guisp=NONE cterm=NONE gui=NONE
if v:version < 801 && !has('gui_running') && !has('nvim')
  set bg=dark
endif
```

Other highlight groups are defined after that, so it can't mess anything up.

**Comment by lifepillar** [comment]
If `set background=dark` is put at the end of the colorscheme, Vim's validation script (`$VIMRUNTIME/colors/tools/check_colors.vim`) will complain with:

```
background: Should not set background option after :hi statement
```

So, that is not a valid workaround.

**Comment by lifepillar** [comment]
I think your workaround is the best one can do. To summarise, the issue may be fixed by adding the following snippet to a colortemplate, just after defining the `Normal` highlight group:

```vim
verbatim
     " Workaround for Vim issue #1710
     if !(has('patch-8.0.0616')                      ||
          \ (has('termguicolors') && &termguicolors) ||
          \ &t_Co < 256                              ||
          \ has('gui_running')                       ||
          \ has('nvim')
          \ )
      set background=dark
    endif
endverbatim
```

I need to think about the best way to integrate this fix into Colortemplate. Perhaps, an option could be added to generate extra code for backward compatibility…

**Comment by mg979** [comment]
Thanks for looking into this. Maybe you could simplify a little bit (it would go after Normal definition if bg==dark):
```vim
verbatim
" Workaround for Vim issue #1710
if !has('patch-8.0.0616') && !has('gui_running') && !has('nvim')
  set background=dark
endif
endverbatim
```

Because:
* gvim and nvim aren't affected
* in other cases, if the patch isn't there, you want to set bg anyway (both termguicolors and notermguicolors are affected)

Unless I'm missing something.

**Comment by mg979** [comment]
This is maybe enough, [in this function](https://github.com/lifepillar/vim-colortemplate/blob/289a8b7b24b59e2cbab3083f95badfe1debd6394/autoload/colortemplate.vim#L797):

```vim
  for l:numcol in s:terminalcolors()
    let l:use16colors = (l:numcol == '16')
    call add(s:colorscheme[l:numcol][l:bg],
          \ join(['hi', s:hi_name(a:hg),
          \       'ctermfg='  . s:term_fg(a:hg, l:use16colors),
          \       'ctermbg='  . s:term_bg(a:hg, l:use16colors),
          \       'guifg='    . s:gui_fg(a:hg),
          \       'guibg='    . s:gui_bg(a:hg),
          \       'guisp='    . s:gui_sp(a:hg),
          \       'cterm=NONE'. (s:has_term_attr(a:hg) ? ',' . join(s:term_attr(a:hg), ',') : ''),
          \       'gui=NONE'  . (s:has_gui_attr(a:hg)  ? ',' . join(s:gui_attr(a:hg), ',')  : '')
          \ ])
          \ )
    " Add snippet to fix vim bug #1710
    if s:hi_name(a:hg) ==# 'Normal' && l:bg == 'dark'
      call extend(s:colorscheme[l:numcol]['dark'], ['',
            \'" Fix Vim bug, see issue #1710',
            \"if !has('patch-8.0.0616') && !has('gui_running') && !has('nvim')",
            \"  set background=dark",
            \"endif", ''
            \])
    endif
  endfor
```

**Comment by mg979** [comment]
I made a [gist](https://gist.github.com/mg979/de03b651042fe12e72f44a6a8d463664) with a possible approach.

It allows to define a key/value pair (as `Full name`, etc) named `Options`, where the value is a list of comma-separated options. They are then split and registered in the s:info dict.

I'm handling this fix as an option, but actually the snippet is inserted by default, unless the option `nofixbg` is declared.

This `Options` line can be used to give directives to colortemplate for tweaking other further

**Comment by lifepillar** [comment]
Thanks. Something like that could probably make it into Colortemplate v2. I'd like to work on a thorough code overhaul, but currently I have no time.

**Comment by mg979** [comment]
Ok thanks, it can be fixed at template level, if one knows about it, so it's not a big issue.

**Comment by lifepillar** [comment]
>Note that I include cterm= in the first section because terminal vim (not neovim or newer vim versions) even tends to mix settings when using termguicolors.

I suppose that you are referring to this issue: https://github.com/vim/vim/issues/1740. AFAICT, it is not fixed in (terminal) Vim, not even in recent versions. Good to keep in mind, because I am working on v2, which will change how colorschemes are generated (and, hopefully, it will fix your issue as well).

**Comment by mg979** [comment]
Maybe you can also check this

https://gist.github.com/romainl/5cd2f4ec222805f49eca

another colorscheme generator, I think it also tries to address the same bug.

**Comment by lifepillar** [comment]
Noted, thanks.

**Comment by lifepillar** [comment]
I have made some tests. The bug happens when

- `background` is `dark` and `hi Normal ctermbg=NNN` is executed, with `NNN` equal to `7`, `9`,  or in the range`10`–`255`; or

- `background` is `light` and `hi Normal ctermbg=NNN` is executed, `NNN` equal to `8` or in the range `0`–`6`.

I assume that patch-8.0.0616 mentioned above fixes it, and that NeoVim and the various gVims are unaffected. The value of `t_Co` does not seem to influence the results.

Colortemplate v2 will generate code to deal with such cases automatically.

**Comment by mg979** [comment]
Ok thanks

**Comment by lifepillar** [comment]
@mg979 If you feel adventurous, the `v2-dev` branch should address this issue properly. Note that the branch is a thorough rewrite, with some incompatibilities with the current master. Your colortemplates should build with a couple of additional warnings. Note also that you'll likely need Vim 8.1 to enjoy the new streamlined interface ;)

**Comment by mg979** [comment]
Generally I use vim 8.0, but I'll give it a try. Will final 2.0 be backwards compatible in any case?

**Comment by lifepillar** [comment]
>Generally I use vim 8.0, but I'll give it a try.

The new release will make use of `:help window-toolbar`, which is pretty new (I am not sure Vim 8.0 has it). If the window toolbar feature is not available, you may continue using the `:Colortemplate[!]` command as before. Let me know if you encounter any issues.

>Will final 2.0 be backwards compatible in any case?

There are several new features, but the syntax is still the same and, as I said, templates should still build without errors (just a couple of warnings). But warnings are there for a reason. One of the main changes is that the `Terminals colors` key has become a no-op. There is a new `Variant` directive instead, which you may use (repeatedly) anywhere in your document. So, if you currently have:

```
# [Other metadata]
Terminal colors: 256
Background: dark
Color: black #333333 ~ 0
Color: white #fafafa ~ 15
Normal white black
```

you may simply remove the `Terminal colors` line, or replace it with a `Variant` directive as follows:

```
# [Other metadata]
Variant: gui 256
Background: dark
Color: black #333333 ~ 0
Color: white #fafafa ~ 15
Normal white black
```

`Background` directives may also be used repeatedly anywhere, and they accept a new value: `any`.  So you may write:

```
Background: any
# Definitions for both backgrounds
Background: dark
# Definitions for dark background
Background: any
# Definitions for both backgrounds again
```

Combining `Variant` and `Background` gives you great flexibility:

```
Variant: gui
Background: any
# Definitions for both backgrounds, apply only to GUI
Background: dark
# Definitions for dark background, apply only to GUI
Variant: gui 256 16
# Definitions for dark background, apply to GUI, 256 colors and 16 colors variants
Background: any
Definitions for both backgrounds, apply to GUI, 256 colors and 16 colors variants
```

Another important change is that anything before the first `Background` or `Variant` directive is considered “global” and put at the start of the resulting colorscheme. One may put `verbatim` blocks or linked group definitions there.

There is a new `Term Colors` key to specify the 16 ASCII colors for Vim's terminal windows, so you don't need `verbatim` blocks for that any longer, e.g.:

```
Term Colors: black red green yellow blue magenta cyan white
Term Colors: brightblack brightred brightgreen brightyellow
Term Colors: brightblue brightmagenta brightcyan brightwhite
```

There is a new `Neovim` key: when set to `yes`, additional code to support NeoVim is generated. That includes code for terminal colors and Neovim-specific highlight groups (if present in the template). So, if you currently have:

```
verbatim
if has('nvim')
endverbatim
TermCursor -> Cursor
TermCursorNC -> Cursor
verbatim
endif
endverbatim
```

you may just remove the `verbatim` blocks.

There are many other changes (italics is detected automatically, tabs are not used, color statistics are computed separately, validation is performed using Vim's `colors/tools/check_colors.vim` script, etc… Try typing `3ga` with the cursor on a Color line!). I'm nearly ready to ship, I just have to update the documentation.

Ah, the `Palette` keyword has been removed, too. A problem with that is that the generated colors had hard-coded default names. I didn't like that. I hope to find a better way to generate colors, but for now the corresponding functionality is broken.

**Comment by mg979** [comment]
I'm trying it.. some feedback:

* in vim 8.0, if I run `Colortemplate!` I get an error (unknown function setbufline)
* it works in vim 8.1
* I appreciate that it doesn't open all those stats in a new tab, and that the `Source` button opens the colorscheme in a split instead of a new tab, but I'd also appreciate if the command `Colortemplate!` did the same (in a split).

**Comment by mg979** [comment]
Also, unfortunately the bug isn't fixed this way. The code generates
```vim
if (has('termguicolors') && &termguicolors) || has('gui_running')
```

and the fix is only contained in the `t_Co` section, but terminal `termguicolors` is also affected by the bug. Only gui and neovim are not.

I use this snippet in the termguicolors/gui section:
```vim
if !has('patch-8.0.0616') && !has('gui_running') && !has('nvim')
  set background=dark
endif
```

**Comment by lifepillar** [comment]
Thanks for the feedback, I'll test it against Vim 8.0 and see what I can fix.

>`Validate` says there are missing fg elements but it's not true.

`Validate` just runs `runtime colors/tools/check_colors.vim` (I removed validation code from Colortemplate because it didn't make sense to duplicate functionality). I have recently submitted a [pull request](https://github.com/vim/vim/pull/4432) to improve the validation: please check that instead.

**Comment by mg979** [comment]
A bug? With this:
```
Color:	    skyblue		SkyBlue ~
```

I get this on first run:

![Imgur](http://i.imgur.com/1H6NNVx.png)

and this on subsequent runs:

![Imgur](http://i.imgur.com/CFSwK3o.png)

**Comment by lifepillar** [comment]
Yes, please try the current master, which should fix it.

**Comment by mg979** [comment]
Thanks. One more thing: in vim 8.1 the window toolbar doesn't disappear if I change buffer inside the same window and it's not a colortemplate file.

**Comment by lifepillar** [comment]
>the window toolbar doesn't disappear if I change buffer

The window toolbar is window-specific (see `:help window-toolbar`). There's a close button on the right if you wish to close it. Perhaps I will add autocommands to hide it when switching buffers…

**Comment by mg979** [comment]
If it's shown automatically, I think it should also be removed automatically...
But there's a bigger problem :).

In termguicolors terminal, italics are broken. The code generates:
```
      if s:italics
        hi Identifier gui=italic
      endif
```

But in terminal `cterm` value is used, also with `termguicolors`.

**Comment by lifepillar** [comment]
Good catch. I'll fix that.

**Comment by lifepillar** [comment]
Fixed.

**Comment by mg979** [comment]
Thanks

**Comment by lifepillar** [comment]
I have tried the current `v2-dev` branch with Vim 8.0.0197 and all the commands appear to work, except `ColortemplateValidate`, which does nothing because there is no `check_colors.vim` script in that version.

You may set `g:colortemplate_quiet=0` if you want the generated color scheme to be opened automatically after building it. When you learn to trust Colortemplate, I think that you won't want to look at the generated code so much any more ;-)

You were mentioning that a few toolbar items (Build and Build!) were not working (in Vim 8.1, I guess?). I cannot reproduce it: if you still do, I would appreciate if you could share more details about it and perhaps, some minimal template to reproduce.

**Comment by mg979** [comment]
I tried it again with v8.0 and `Colortemplate!` works. Build and Build! weren't working before I updated (the window bar looked different), but now there is only Build! and it works.

Only in one occasion I could not build (error about vim bdelete), otherwise I had no problems.

**Comment by lifepillar** [comment]
Ok! If you want to provide more feedback, please open a new issue with v2-dev in the title. Thanks!

**Comment by mg979** [comment]
Thanks, one last thing here:
```
|1 col 1 warning| 'Term Colors' key missing for dark background
```
what would that be?

**Comment by lifepillar** [comment]
That’s a new key to specify the 16 ASCII colors for Vim terminal windows. Your comment reminds me that I forgot to document it…

```
Term Colors: myblack myblue …
Term Colors: … mybrightwhite
```

You may repeat the key to avoid long lines, but overall you must provide 16 color names.
