### ISSUE TITLE
Possible to have easy if/else blocks?

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-colortemplate#14]
If I have blocks like:

```
verbatim
if &termguicolors || has('gui_running')
endverbatim
	FoldColumn		skyblue		nightblue
verbatim
else
endverbatim
	FoldColumn		skyblue		none
verbatim
endif
endverbatim
```

I think this format would be more readable:
```
If &termguicolors || has('gui_running')
	FoldColumn		skyblue		nightblue
Else
	FoldColumn		skyblue		none
Endif
```

That is, to treat uppercase If/Else/etc as one-line verbatim blocks. I tried it to implement it myself but I couldn't do it.

**Comment by lifepillar** [comment]
You don’t do that the way you show it. Colortemplate v2 (currently in beta) provides the `Variant` keyword;

```
Variant: gui
# Defs that apply only in GUI or with termguicolors set
Variant: 256 16
# Defs that apply to terminals
```

See `:help colortemplate-variants`.

Your specific example aside, I’m not against adding support for conditionals.

**Comment by mg979** [comment]
Thanks for answering. But using variants would force me to redefine each group for each variant? I'd stick with the verbatim blocks at that point.

These conditional blocks could also be used to check user options, like filetype specific highlight, contrast, etc.

By the way it's just a readability issue, so not a big problem.

**Comment by lifepillar** [comment]
>But using variants would force me to redefine each group for each variant?

No, a `Variant` directive specifies to which variants (true-color, 256-color, 16-color, and so on) the subsequent definitions apply. So, if you have different colors for `FoldColumn` only, you can do:

```
Variant: gui  # Only GUI or termguicolors set
	FoldColumn		skyblue		nightblue
Variant: 256 16  # 256- and 16-color terminals
	FoldColumn		skyblue		none
Variant: gui 256 16  # All three variants
# All the remaining highlight groups
```

It is a declarative way to define conditional behaviour. Your code would generate something similar to this in v2:

```
if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &termguicolors || has('gui_running')
    hi FoldColumn guifg=#ffffff guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  else
    hi FoldColumn guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  endif
endif

if s:t_Co >= 256
  if &termguicolors || has('gui_running')
    hi FoldColumn ctermfg=231 ctermbg=16 cterm=NONE
  else
    hi FoldColumn ctermfg=231 ctermbg=NONE cterm=NONE
  endif
endif
```

Your check is clearly redundant because it is performed automatically by Colortemplate.

>These conditional blocks could also be used to check user options, like filetype specific highlight, contrast, etc.

Sure, they may be convenient. I'll work on that.

**Comment by lifepillar** [comment]
The current master now implements (and will soon document) `#if`, `#else`, `#elseif` and `#endif`. They work like one-line verbatim blocks. The keywords must appear at the beginning of a line. For instance:

```
#if get(g:, 'transparent_foldcolumn', 0)
	FoldColumn		skyblue		nightblue
#else
	FoldColumn		skyblue		none
#endif
```

**Comment by lifepillar** [comment]
My [WWDC17](https://github.com/lifepillar/vim-wwdc17-theme/blob/master/template/wwdc17.colortemplate) color scheme now uses them.

**Comment by lifepillar** [comment]
I have also added `#let` and `#unlet`, as they're handy. I hope this won't degenerate with people asking me to reimplement the whole of VimScript :>

**Comment by mg979** [comment]
Works great, thanks!

> I hope this won't degenerate with people asking me to reimplement the whole of VimScript :>

Maybe just `#call` :)?

**Comment by lifepillar** [comment]
You've got it! Check out the current master.

**Comment by mg979** [comment]
Thanks, hoping I'm not being picky, `#` is used for comments too, maybe `&` or something else would be better.

**Comment by lifepillar** [comment]
I like `#` because it reminds me of C macros. Highlighting should make the distinction clear. Could be `@` instead.

**Comment by mg979** [comment]
For me it's fine, thanks.
