### ISSUE TITLE
v2 behavior differs from v1

### ISSUE THREAD

**Issue by caksoylar** [lifepillar/vim-colortemplate#15]
After upgrading to v2 (commit [b0e814](https://github.com/lifepillar/vim-colortemplate/commit/b0e8145ad3b3889139a50ec29dea42929427cf4e)) the color definitions are different for highlight groups with `none` values.

As an example we can compare `SignColumn` for [v1](https://github.com/caksoylar/vim-mysticaltutor/blob/f0f6700e5b725e927257a6428db9d03b4516b82e/colors/mysticaltutor.vim#L61) and [v2](https://github.com/caksoylar/vim-mysticaltutor/blob/1ce75251172338f9e0de985df0cd2e411ccbdbff/colors/mysticaltutor.vim#L59). It looks like `v2` skips `ctermfg`/`ctermbg` definitions for the `gui` variant, and this lets these values be overridden by the default color scheme highlights (that are built into Vim, not defined in `colors/default.vim`.

Output of `verbose hi SignColumn` in v1:

    SignColumn     xxx term=standout
        Last set from [...]/colors/mysticaltutor.vim line 61

v2:

    SignColumn     xxx term=standout ctermfg=14 ctermbg=242
        Last set from [...]/colors/mystical_v2.vim line 59

It could be intended behavior, then template writers can be expected to specify `fg` and `bg` to `hl-Normal` values. But I am not sure that can exactly replicate the old behavior for cases where overriding certain highlights are intended, like `CursorLine`, `Visual` or diff highlights.

**Comment by lifepillar** [comment]
>After upgrading to v2 (commit b0e814) the color definitions are different

That's intended behaviour.

>It looks like v2 skips `ctermfg`/`ctermbg` definitions for the `gui` variant

Yes, it does. In GUI Vim, or when `termguicolors` is set, Vim should use only `guifg` and `guibg`, so the values of `ctermfg` and `ctermbg` do not matter.

>It could be intended behavior, then template writers can be expected to specify `fg` and `bg` to `hl-Normal` values. But I am not sure that can exactly replicate the old behavior for cases where overriding certain highlights are intended, like `CursorLine`, `Visual` or diff highlights.

I am not sure I understand this paragraph. The `Normal` highlight group must always be defined: Colortemplate gives an error if you don't.  Are there cases where you get visually different results compared to v1? If so, could you please provide a minimal example to reproduce the issues?

**Comment by mg979** [comment]
I think @caksoylar is right, `ctermbg=` and `ctermfg=` don't matter, but `cterm=` does, it's the same issue that was present with italics if you remember.

Terminal vim will use `cterm=`/`term=` settings even with `termguicolors`, you can skip  `ctermbg=` and `ctermfg=`, but I don't think you can skip `cterm=`/`term=`.

**Comment by caksoylar** [comment]
Sorry, I wasn't very clear on that last paragraph. I meant replacing definitions like `SignColumn none none` with "equivalent" definitions such as `SignColumn fg bg` or `SignColumn black white` (where `black white` are what `Normal` are defined as).

As for visual differences, yes, as a result of the differences in the outputs I have different highlights, for v1:
![image](https://user-images.githubusercontent.com/7876996/58914091-7ecb0800-86d2-11e9-87bd-3b757fc5ace1.png)

For v2:
![image](https://user-images.githubusercontent.com/7876996/58914115-91ddd800-86d2-11e9-9be3-2fb90d798842.png)

It looks like Vim picks up highlights from `cterm` groups if `gui` values are `NONE` by default. So if we have `SignColumn     xxx term=standout ctermfg=14 ctermbg=242` with the v2 output as in my OP, the background turns out gray.

**Comment by lifepillar** [comment]
Ok, I can reproduce it. Does it happen because you have `SignColumn none none` in your template? Or otherwise how are you defining the relevant highlight groups in your template?

**Comment by caksoylar** [comment]
Yes, I have `SignColumn none none`, which you can see [here](https://github.com/caksoylar/vim-mysticaltutor/blob/master/template/mysticaltutor.colortemplate#L92). It also happens for other highlight groups defined similarly, such as `CursorColumn` which you can see there.

**Comment by lifepillar** [comment]
Thanks, I'll fix it.

**Comment by lifepillar** [comment]
Can you try the current master? Please reopen if it does not fix this issue.

**Comment by caksoylar** [comment]
Thanks for the fix, works as expected now. I am also liking v2 so far. `Variant` and the new if/else statements make writing easier and the new toolbar is very handy.
