### ISSUE TITLE
Requirement for `set hidden`... Why?

### ISSUE THREAD

**Issue by filbranden** [lifepillar/vim-colortemplate#18]
Requirement for `set hidden` makes things awkward in a way...

Readme suggests starting with `:edit templates/default_clone.colortemplate` but that fails if `hidden` is not set.

Is the expectation that this should be set in our `.vimrc`?

Is perhaps using `setlocal bufhidden=hide` only on the `ft=colortemplate` buffer an alternative option that would solve a similar problem?

Otherwise, can you please describe what the exact problem that requires `set hidden` is? (A reproducer for the problem when that's unset and that check commit is absent would be useful.) I'd be happy to look at other possibilities.

Cheers!
Filipe

**Comment by filbranden** [comment]
Another workaround, to open the colortemplate file from the command line...:

```
$ vim --cmd 'set hidden' templates/default_clone.colortemplate
```

**Comment by lifepillar** [comment]
There are situations in which Colortemplate needs to switch between unsaved buffers. I’ll check whether it can be done with a buffer option, or otherwise relax the global `hidden` requirement.

**Comment by filbranden** [comment]
Thanks for the fix! Glad that `bufhidden` was enough to fix it.
