### ISSUE TITLE
Document that :Colortemplate requires special filetype

### ISSUE THREAD

**Issue by jan-warchol** [lifepillar/vim-colortemplate#22]
I've just hit a problem described in #5 - I had opened a template file *before* installing the plugin, so the filetype was not set and `:Colortemplate` was reported as missing. @lifepillar I think it should be explained in repo README (and perhaps in vim help, too - I haven't found it in getting started).

**Comment by lifepillar** [comment]
Sorry for taking so long to address this (this somehow fell off my radar). Now the Readme and the help file mention that.

Thanks for your feedback!
