### ISSUE TITLE
Italics don't work in neovim

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-colortemplate#23]
Generated colorschemes have this line:

    let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

But in neovim this will not work (it needs ` || has('nvim')` as well).

**Comment by lifepillar** [comment]
Have you added this line in your Colortemplate?

```
Neovim: yes
```

**Comment by mg979** [comment]
Yes it works, thanks.
