### ISSUE TITLE
Explicitly inform users on how to install this plugin

### ISSUE THREAD

**Issue by wadkar** [lifepillar/vim-colortemplate#25]
Great hackable tool!

It might help potential users if there's a sentence or two on how to install this extension. For example,

`Plug 'lifepillar/vim-colortemplate'`

Unless, we're supposed to fork it and use it?
Always happy to send a PR.

**Comment by lifepillar** [comment]
Installation does not require anything special. Just download and put inside Vim's plugin folder.

Anyway, the wiki should be open for editing. Feel free to create a page with installation instructions, and I will link it from the Readme.

**Comment by wadkar** [comment]
Huh, when I click on the wiki button, it redirects to the homepage. Is wiki enabled for this repository?

I know installation doesn't require anything special, I just thought explicitly calling it out in README will be helpful. If you don't think it's a good idea, your call.

**Comment by lifepillar** [comment]
I have enabled a public wiki now.

**Comment by wadkar** [comment]
Done: https://github.com/lifepillar/vim-colortemplate/wiki/FAQs

Reopening this, so you can close it with a commit.

**Comment by lifepillar** [comment]
Added a link in the Readme. Thanks!
