### ISSUE TITLE
Clarify documentation on Variant

### ISSUE THREAD

**Issue by cideM** [lifepillar/vim-colortemplate#27]
I don't understand what the documentation on the Variant feature is supposed to mean

> For example, if you
> declare:
> >
> 	Variant: 256 88
> <
> then you may use only base-256 colors between `0` and `87`. On the other hand,
> if you declare:
> >
> 	Variant: 256 8 4
> <
> you will be able to use all base-256 colors, but only the first four base-16
> colors.

When `256 88` means base-256 but only the first 87, then why doesn't `256 8 4` mean base-256 but only the first 4? [Later on](https://github.com/lifepillar/vim-colortemplate/blob/master/doc/colortemplate.txt#L315) it's explained what output is generated from these values, but here it seems that declaring multiple values just renders multiple `t_Co` blocks. That would imply that declaring multiple number values for the same Variant is redundant since if color definitions apply to a `t_Co >= 8` they automatically also apply for `256`. Meaning `256 8 4` wouldn't make much sense since the `>= 4` includes the 8 and 256 anyway.

Buuuuuuuuuuuuuut I'm guessing I'm misunderstanding something here.

**Comment by lifepillar** [comment]
>When `256 88` means base-256 but only the first 87, then why doesn't `256 8 4` mean base-256 but only the first 4?

It makes sense (I believe) if you keep in mind that each `Color` declaration has three values:

1. a “GUI” value for terminals supporting millions of colors;
2. an “xterm” value for terminals supporting more than 16 colors (but not millions of colors);
3. and an ANSI color value for terminal with no more than 16 colors.

When you write `Variant: 256 88` you are instructing Colortemplate to apply the definitions following that directive to terminals supporting 256 colors and 88 colors, that is, terminals of category 2. Similarly, `Variant: 256 8 4` means that Colortemplate should generate definitions for terminals supporting 256 colors (category 2) and terminals supporting 8 and 4 colors (category 3). When two or more variants fall in the same category, the one with least colors is the one that limits you.

Consider this (incorrect) example:

```
Color: foo #fafafa 236 15
Variant: 256 88 8 4
Normal foo foo
```
This would generate the following code:

```vim
if t_Co > k
```

**Comment by cideM** [comment]
Hm alright but I still don't see how the code below, taken from the docs, would apply:

```
        if &t_Co >= 256
	  hi Normal ctermfg=231 ctermbg=16 cterm=NONE
	  finish
	endif

	if &t_Co >= 8
	  hi Normal ctermfg=LightGray ctermbg=Brown cterm=NONE
	  finish
	endif
```

If `t_Co` is 256 then the 2nd if block would also apply and thereby generate a competing `Normal` highlight group.

**Comment by lifepillar** [comment]
>If t_Co is 256 then the 2nd if block would also apply and thereby generate a competing Normal highlight group.

No, the `finish` command ends the script at that point, so the `if` blocks are mutually exclusive. Using `finish` is a just an optimization to make the color scheme load faster.

**Comment by cideM** [comment]
Oh wow I totally overlooked that, sorry! Thank you for clarifying this :+1:
