### ISSUE TITLE
race condition with `:Colortemplate!` in neovim nightly

### ISSUE THREAD

**Issue by beardedsakimonkey** [lifepillar/vim-colortemplate#28]
Sometimes, when running `:Colortemplate!` (usually takes two calls to reproduce, but sometimes it happens on the first call.  It's very race-conditiony), it will fail with this error:
```
Error detected while processing function colortemplate#make[56]..<SNR>72_print_error_msg[1]..<SNR>72_clearscreen:
line    1:
E315: ml_get: invalid lnum: 199
Press ENTER or type command to continue
```

and i'm left on a hidden, unnamed buffer with only 2 lines:
```
" Name:         Gruvburn
" Author:       Myself <myself@somewhere.org>
```

Commenting out these lines seems to fix this:
https://github.com/lifepillar/vim-colortemplate/blob/1edc68bd725bfc65e259f3681b83d4db46e4e1ab/autoload/colortemplate.vim#L140-L141

I cannot reproduce this on vim (where `exists('*appendbufline') == 1`)

**Comment by beardedsakimonkey** [comment]
nevermind: looks like this is being caused by vim-language-server/nvim-lsp

**Comment by beardedsakimonkey** [comment]
for posterity: you can work around the issue with something like this:
```
autocmd vimrc BufWritePost *.colortemplate set eventignore=FileType | Colortemplate! | set eventignore=
```

**Comment by lifepillar** [comment]
Can you reproduce this in NeoVim *without* nvim-lsp? Did you close this because it cannot be fixed in Colortemplate? I do not understand what the root cause is (I am not using NeoVim).

**Comment by beardedsakimonkey** [comment]
sorry, just noticed your reply.

> Can you reproduce this in NeoVim without nvim-lsp?

no i could not

> Did you close this because it cannot be fixed in Colortemplate? I do not understand what the root cause is (I am not using NeoVim).

it might be fixable from Colortemplate.  I'm also not sure what the root cause is. I'll take a look tomorrow.

**Comment by beardedsakimonkey** [comment]
not sure if this is an acceptable change, but this patch seems to work around it:
```diff
diff --git a/autoload/colortemplate.vim b/autoload/colortemplate.vim
index e6217d7..1a99bbc 100644
--- a/autoload/colortemplate.vim
+++ b/autoload/colortemplate.vim
@@ -112,7 +112,7 @@ endf
 " }}}
 " Buffer and file manipulation {{{
 fun! s:do_make_buffer()
-    botright 1new +setlocal\ ft=vim\ norl\ nowrap\ bh=hide
+    botright 1new +setlocal\ norl\ nowrap\ bh=hide
     if s:getopt('use_tabs')
       setlocal noet
     else
@@ -168,6 +168,7 @@ else
   endf

   fun! s:reindent_buffer(bufnr)
+    silent execute a:bufnr "set ft=vim"
     silent execute a:bufnr "bufdo norm gg=G"
   endf
```
