### ISSUE TITLE
Hash sign (#) is overloaded in Colortemplate: use new symbol for comments

### ISSUE THREAD

**Issue by lifepillar** [lifepillar/vim-colortemplate#30]
Since commit 53b56ba4f28886665c49c96f8a006e5c1f6f5658 Colortemplate has used `#` as the prefix for convenient one-line verbatim blocks (`#if`, `#let`, etc.). But Colortemplate uses `#` also for comments (and for hex colors—but that is a context-sensitive use). As pointed out by @mg979 in https://github.com/lifepillar/vim-colortemplate/issues/14#issuecomment-498843325, it would be better to use different symbols. I like`#if`, `#let`, etc. because they remind me of C macros. So, I plan to introduce a new symbol for line comments and deprecate `#` for comments. The question is: which symbol?

My initial choice was `%`, as in TeX (Knuth is always right 🙂). But then I thought that`%` might be useful in future extensions of Colortemplate, e.g., to specify colors using percentages (?).

My current preference goes to `;`, as in assembly (yes, I know: C, assembly… I am old school).

I will leave this issue open for comments for a while.

For reference, these are commonly used symbols from various programming languages ([source](https://www.gavilan.edu/csis/languages/comments.html)):

```
;   As in Algol 60 and assembly
--  As in SQL
//  As in C/C++
!   As in FORTRAN 90
'   As in Visual Basic .NET
%   As in TeX
```

**Comment by lifepillar** [comment]
The current master recognizes `;` as a line comment (in addition to `#`), so you can try it. This should be considered a *tentative* addition: do not use it (yet) in your templates!

**Comment by arzg** [comment]
My personal preference is for `--`, as it feels like the use of a dash in text to indicate an aside – like so.

**Comment by arzg** [comment]
Here’s a rudimentary poll:

🔴 for `;`
⚫ for `--`
🟤 for `//`
❗ for `!`
🟢 for `'`
⚪ for `%`

**Comment by lifepillar** [comment]
I like `--`, too (as I’m old school, I am partial to SQL). The minor advantage of `;` is that it is a single character. On the other hand, `-` is already in Colortemplate’s alphabet, so with `--`, we wouldn’t “waste” a symbol.

**Comment by lifepillar** [comment]
@arzg Thanks for the creative use of emojis for the poll :-)

**Comment by lifepillar** [comment]
And the winner is… `;` (yes, I know, I am *also* anti-democratic; on the other hand, who gets more votes is not always elected, right?).

Joking aside, there are a few technical reasons why I opted for `;` instead of `--`. Anyway, start updating your color schemes! (The old `#` symbols is still supported, but will raise a warning).
