### ISSUE TITLE
Includes with parameters?

### ISSUE THREAD

**Issue by arzg** [lifepillar/vim-colortemplate#31]
Hi,

I recently found myself in a situation in which I needed to pass parameters to an `Include`d template that contained an auxfile block. When built with colour scheme `a`, I wanted `@guired` to be used in a particular place in this auxfile. However, when built with colour scheme `b`, `@guired` should be replaced with `@guigreen`. In other words, I need some way to vary a small portion of the contents of an auxfile/Include.

**Comment by arzg** [comment]
Here’s an example syntax:

```
# _statement.colortemplate
params fg bg style
Statement $fg $bg $style
```

```
# one.colortemplate

# -snip-

Include: _statement blue black bold
# which expands to
Statement blue black bold
```

```
# two.colortemplate

# -snip-

Include: _statement pink white italic
# which expands to
Statement pink white italic
```

**Comment by lifepillar** [comment]
You may deal with duplication in your auxiliary files by using multiple `auxfile` blocks with the same path: the blocks are concatenated in the order in which they are encountered during parsing. For instance:

```
# _aux.colortemplate
auxfile foo.vim
" Text common to all versions of foo.vim
endauxfile
```

```
# one.colortemplate
auxfile foo.vim
" Text specific to one.colortemplate
endauxfile
Include: _aux.colortemplate
auxfile foo.vim
" More text specific to one.colortemplate
endauxfile
```

```
# two.colortemplate
auxfile foo.vim
" Text specific to two.colortemplate
endauxfile
Include: _aux.colortemplate
auxfile foo.vim
" More text specific to two.colortemplate
endauxfile
```

Does that help?

**Comment by arzg** [comment]
Yep, that completely solves it; thanks for the hint. For future reference, is this mentioned in the documentation anywhere?

**Comment by lifepillar** [comment]
No, I will document that.
