### ISSUE TITLE
Can you generate a colortemplate based on the current colorscheme?

### ISSUE THREAD

**Issue by idbrii** [lifepillar/vim-colortemplate#32]
It would be great for converting manually-created colorschemes to colortemplate if colortemplate had a command to generate your initial template.

**Comment by lifepillar** [comment]
That’s an intetesting idea, though it sounds non-trivial to implement reliably. I will think about it. PRs/suggestions welcome!

**Comment by lifepillar** [comment]
There is some code in the current master to implement this feature. It processes the currently defined highlight groups and generates a colortemplate document.

Code needs to be ironed out, but it works. Expect bugs. Feedback welcome.

Do not forget to read the documentation! (See `:help colortemplate#import#run()`).
