### ISSUE TITLE
Rendering glitches in Neovim

### ISSUE THREAD

**Issue by cideM** [lifepillar/vim-colortemplate#33]
I always found it strange that no one else had created an issue so I can only assume that I'm the only one plagued by this. But I have very strange rendering glitches where e.g., a single line is suddenly repeated for each line I scroll downwards.

<img width="662" alt="Screen Shot 2020-07-27 at 17 12 07" src="https://user-images.githubusercontent.com/4246921/88558795-50be2b00-d02c-11ea-8c30-d8e16942f679.png">

I've had this for as long as I can remember. I'm on Neovim 
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/vglb2f345siggaxdai8ghlnjx4y428an-neovim-unwrapped-master/share/nvim
"

Run :checkhealth for more info
```
and here are my settings

```
set shell=bash
" https://www.reddit.com/r/vim/comments/25g1sp/why_doesnt_vim_syntax_like_my_shell_files/
let g:is_posix = 1

set wildignore+=*/.git/*,
            \tags,
            \*/node_modules/*,
            \*/build/*,
            \*/dist/*,
            \*/compiled/*,
            \*/tmp/*
set cmdheight=2
set diffopt=algorithm:patience,filler,iwhiteall,indent-heuristic
set expandtab
set fillchars=stl:\ ,vert:\|,fold:\ 
set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
set hidden
set ignorecase
set noshowmode
set updatetime=100
set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
set inccommand=split
set nocursorline
set nonumber
set path-=/usr/include
set shiftwidth=4
set shortmess+=c
set smartcase
set splitbelow
set splitright
set completeopt-=preview
set termguicolors
set undofile

" Automatically resize windows if host window changes (e.g., creating a tmux
" split)
augroup Resize
    autocmd!
    autocmd VimResized * wincmd =
augroup END
" }}}
```

**Comment by lifepillar** [comment]
Can you provide a step-by-step way to reproduce it? I have tried to run `nvim -u your_settings.vim`, then added Colortemplate to `runtimepath` and opened some templates, but I don't see anything wrong when scrolling or performing other actions.

Even before that, have you tried with a different terminal, to rule out that it's a terminal-related issue?

**Comment by beardedsakimonkey** [comment]
I've experienced this as well, but I think it might be specific to neovim 0.5.  For me, setting `let g:colortemplate_toolbar = 0` fixes this.

**Comment by lifepillar** [comment]
That's strange. AFAIK, Neovim does not support window toolbars, so that setting should not have any effect, because toolbars are not enabled anyway.

**Comment by lifepillar** [comment]
I am using Neovim 0.4.3: perhaps, toolbars were added in v0.5? If that is the case, the OP's issue is likely a Neovim issue.

**Comment by cideM** [comment]
Indeed, the issue is not present in Neovim 0.4.3! I'll create an issue on the Neovim tracker then

**Comment by andymass** [comment]
It's unfortunate that this is not supported in neovim.  I think toolbars are a great feature well-used by vim-colortemplate.
