### ISSUE TITLE
WIP feature: real-time style picker!

### ISSUE THREAD

**Issue by lifepillar** [lifepillar/vim-colortemplate#37]
For a while I have been thinking hard about how nice it would be to be able to update highlight groups in real-time using a style picker inside Vim. I have long pondered about the design and implementation of such a feature (less easy than you may think—especially the design part), but I believe I have finally nailed it (at least, the path is clear in my mind). Thanks to Vim popups and text properties! The code is far from finished and it is not published yet, but this is a draft of how it might look like:

<img width="446" alt="Screenshot 2020-08-30 at 17 56 51" src="https://user-images.githubusercontent.com/1193314/91663731-03315400-eaeb-11ea-8f9b-255b6743c2ee.png">

Not too polished, I know, but I am so excited about this feature! From top to bottom, you see:

- the name of the current highlight group: this may be fixed, or it may change as you move the cursor to pick the highlight group under the cursor;
- RGB “sliders”;
- Information about the current style: hex and term values, whether this is a foreground/background/special color, and letters for attributes (B = bold, I = italic, etc.).
- Recent and favourite colors: the idea is that one could access frequently used colors there (you don't see any colors because the feature does not exist yet).

If you like this idea, or have any questions, please give me some feedback!

**Comment by lifepillar** [comment]
Ok, so a draft of this feature has landed in master! The current iteration looks like this:

<img width="446" alt="Screenshot 2020-09-02 at 23 43 37" src="https://user-images.githubusercontent.com/1193314/92039981-481ceb00-ed76-11ea-9dd2-3cd16e63ccc5.png">

Many things have to be implemented yet (some are visible in the picture, others include adding counts to some mappings, additional panes, additional information about the current color, etc.), but the popup is working and usable.

Use `:ColortemplateStyle` or `:ColortemplateStyle <higlight group>` to invoke it, tweak your colors, yank them if you want (`y`), and close the popup (use `X` to revert your changes, `x` to close with the current colors). The details should be pretty intuitive, and a help pane can be opened with `?`.

Ah, the screenshot above is taken from a 256-color terminal (you can tell that because the GUI color is not shown), but of course one should ideally work in an environment supporting millions of colors. Note that, in the current master, opening the popup raises some (harmless) errors, which I am going to fix soon.

**Comment by habamax** [comment]
Looks awesome!

In Gvim I get minor "rendering" issue, probably due to font:

![image](https://user-images.githubusercontent.com/234774/92078312-ba1d2080-edc6-11ea-92b7-e5ff4a029759.png)


PS, command is not available till you open colortemplate file, I guess this is intentional :)

**Comment by lifepillar** [comment]
>In Gvim I get minor "rendering" issue

Yes, and there are some others (like when `ambiwidth` is `double`). Your issue with `linespace` seems specific to Gvim, though; I cannot reproduce it in MacVim, for example.

I plan to make the bars customizable, eventually. It is probably sensible to provide at least an ASCII-only version. Suggestions for symbols to use are welcome. 

>command is not available till you open colortemplate file,

That's on purpose and documented. (`:help colortemplate-commands`). I want to keep this a pure filetype plugin. I do not want to pay anything, such as loading files from a `plugin` folder, when I am not using Colortemplate.

You can easily define a global mapping, e.g.:

```
nmap gc :<c-u>call colortemplate#style#open()<cr>
```

I should probably document this as well.

**Comment by lifepillar** [comment]
New iteration:

<img width="325" alt="Screenshot 2020-09-04 at 10 25 27" src="https://user-images.githubusercontent.com/1193314/92221646-1010c780-ee9e-11ea-8586-37ce766e4911.png">

What's new:

- you can now increase/decrease the RGB bars at steps between 1 and 99 (just type the new step and press the arrow keys—the current step is displayed below the bars: it's `10` in the screenshot);
- the type of color (foreground/background/special) is now shown in the title, next to the name of the highlight group;
- the pane provides richer information: in particular, it shows the difference (Δ) between the GUI color and its best terminal approximation, and an evaluation of the quality of the GUI and terminal colors against the background of the highlight group. The latter is displayed using up to five stars.
- the popup now keeps track of the position where it was last open.

See `:help :ColortemplateStyle` for the details!

**Comment by lifepillar** [comment]
>In Gvim I get minor "rendering" issue, probably due to font

With the current master, you may use ASCII-only bars by setting `g:colortemplate_slider_ascii = 1`. Or define your own symbols with `g:colortemplate_slider_symbols`. See the help file.

**Comment by habamax** [comment]
Helped me a lot, thx for the Picker!

**Comment by lifepillar** [comment]
The style picker now remembers the 10 most recent colors (in the current session) and an arbitrary number of favorite colors (persistent across sessions):

<img width="328" alt="Screenshot 2020-09-11 at 23 49 27" src="https://user-images.githubusercontent.com/1193314/92975895-9bcfb880-f489-11ea-98b3-f138baeb05a5.png">

**Comment by lifepillar** [comment]
With the added grascale and HSB panes, plus lots and lots of refinements, the style picker is finally complete. A release will follow soon.

<img width="282" alt="Screenshot 2020-09-19 at 21 51 58" src="https://user-images.githubusercontent.com/1193314/93687952-76aefb80-fac2-11ea-8794-22a43fbed5ec.png">
