### ISSUE TITLE
update commentstring to reflect changes from # to ;

### ISSUE THREAD

**Issue by habamax** [lifepillar/vim-colortemplate#38]
Using vim-commentary I get deprecated comments `#` instead of `;`.

https://github.com/lifepillar/vim-colortemplate/blob/c4335e363f7bf7e38d7e755ecd941af219b1cf96/ftplugin/colortemplate.vim#L22

**Comment by lifepillar** [comment]
Ah ah, sorry. I was on mobile, and didn't read either the subject or the full text of your comment, hence my dumb reply. Anyway, this is fixed now!

**Comment by habamax** [comment]
np, :)
