### ISSUE TITLE
make highlighting consistent # vs ;

### ISSUE THREAD

**Issue by habamax** [lifepillar/vim-colortemplate#39]
The old comment with vim code is highlighted differently with the new one:

![image](https://user-images.githubusercontent.com/234774/92085171-1f760f00-edd1-11ea-8270-d1240d988112.png)

**Comment by habamax** [comment]
I was wrong, `#` wasn't treated as comment in prev versions, so it should stay `#`

**Comment by lifepillar** [comment]
That's correct. The whole purpose of the changing the comment symbol was to distinguish between one-line verbatim blocks (`#if`, `#else`, etc.), which are *not* comments, from comments.
