### ISSUE TITLE
Add airline support

### ISSUE THREAD

**Issue by lifepillar** [lifepillar/vim-colortemplate#4]
(Original issue from @jordwalke at https://github.com/lifepillar/vim-colortemplate/issues/2)

>Should this template include vim-airline support?

**Comment by lifepillar** [comment]
I have addressed this by implementing “aux file blocks”, which generalize the idea of documentation blocks. Aux file blocks can be used to generate any additional external files. If you put something like this in your template:

```vim
auxfile autoload/airline/themes/mycolorsheme.vim
" Anything can go here
endauxfile
```

then `:Colortemplate path/to/output/dir` will create a file at the specified path, relative to the output directory. The content between `auxfile` and `endauxfile` is interpolated as in verbatim blocks, so you may use, for example, `@shortname` to refer to the name of your colorscheme, or things like `@guiblack`, `@term16black`, `@term256black` to refer to the GUI value, base-16 value, base-256 value, respectively, of a color called “black”.

This feature is not documented yet, but it should be working fine.

Now, I am not using Airline or any other status line plugins, so I am not going to create a template for it, but I will gladly accept pull requests. [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes) might be a good starting point.

**Comment by wadkar** [comment]
This is cool. Let me see if I can add something for this to the FAQ or create a "vim-colortemplate" theme in vim-airline-themes.

**Comment by lifepillar** [comment]
I am closing this, as aux files address the issue in the general way. If someone feels like submitting an aux file template specifically for Airline or other plugins, they may open a pull request.
