### ISSUE TITLE
Neovim: E518: Unknown option: balloonexpr=colortemplate#syn#balloonexpr()

### ISSUE THREAD

**Issue by kkga** [lifepillar/vim-colortemplate#41]
I'm getting the following error on loading the filetype plugin. I tried both on Neovim stable 0.4.4 and nightly 0.5.0.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/1460122/93605451-6ff38c00-f9cf-11ea-9c3c-c5fc35b2a950.png">

```
❯ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina
```

Quick look at `:help 'balloonexpr'` shows that it's removed?
<img width="623" alt="image" src="https://user-images.githubusercontent.com/1460122/93606110-4a1ab700-f9d0-11ea-91f5-55636ce44de6.png">

**Comment by beardedsakimonkey** [comment]
i noticed when doing `:call colortemplate#syn#toggle()` i get a number of errors that seem to be caused by using vim features that are not available in neovim, such as the object literal syntax `#{ ... }` and the text properties API `call prop_type_add()`.

**Comment by lifepillar** [comment]
Set `g:colortemplate_higroup_balloon` to `0`.

I will add a check to prevent those errors.

**Comment by lifepillar** [comment]
You shouldn't get any errors with the current master, regardless of the value of `g:colortemplate_higroup_balloon`.

**Comment by beardedsakimonkey** [comment]
works like a charm, thanks for the quick fix!
