### ISSUE TITLE
Include is not colortemplateKey

### ISSUE THREAD

**Issue by habamax** [lifepillar/vim-colortemplate#42]
Shouldn't `Include:` be a `colortemplateKey`?

![image](https://user-images.githubusercontent.com/234774/93709362-69d3eb80-fb46-11ea-9d0a-13ad1a3b3d08.png)

**Comment by lifepillar** [comment]
`Include` is also the name of a highlight group (`:help group-name`). In the syntax file, it takes precedence also in that context. I'll fix it.
