### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by il-mich** [lifepillar/vim-colortemplate#44]
It's not really clear how one is supposed to use the tool and how to interact with it. What's trivial and obvious for the developer may be obscure to the user with less (or no) background.

Eg.
I wasn't able to reproduce the pop up interaction, either in Nvim or Vim from terminal (URxvt) or GVim, all of them with and without my configs. And because of the missing docs I don't know if I'm doing something wrong or if there is a bug.

**Comment by lifepillar** [comment]
? Colortemplate has extensive documentation: see `:help colortemplate.txt`. If there is some part of the help file that needs improvement, please point that out.

The popups and the style picker do not work in Neovim.

In general, although I try not to make the plugin break in Neovim (e.g., by disabling unsupported functionality to avoid runtime errors), Colortemplate officially supports only Vim. I am not using Neovim, and the time I can devote to this plugin is limited.

**Comment by il-mich** [comment]
> Colortemplate has extensive documentation: see :help colortemplate.txt.
I was looking for it in the Wiki section of GitHub, my bad!

Popup and picker don't seem to work in Vim either, how am I supposed to open them?

**Comment by lifepillar** [comment]
>Popup and picker don't seem to work in Vim either, how am I supposed to open them?

`gl` toggles highlight group information: as you move the cursor, such information is displayed in the command line; if you hover with the mouse on some text, a popup should open with the same information. This works by default in `colortemplate` buffers: to make it work globally you need to define your own global mapping, and also set `balloonexpr`. This is documented under `:help colortemplate-mappings` (scroll towards the end of the section).

The style picker can be opened by typing`gs`. Again, this works only in `colortemplate` buffers. See the above help reference for a suggestion on how to set up a global mapping.

If this does not solve your issue, please be more specific than “they don't seem to work” by providing step-by-step instructions to reproduce your problem.

**Comment by il-mich** [comment]
Using `gl` and `gs` makes the popups appear as expected, but they are not enabled by default.

I have Vim 8.2.735 in URxvt on a Alpine Linux machine. For testing purposes my vimrc consists of the Plug call to this repo and `set mouse=a`.
- I open `dark.colortemplate` in Vim, the popups do not appear as I hover.
- `:set ft=colortemplate` does not enable them.
- The `gl` and `gs` commands then make the popups work.

I don't know why (in my Vim at least) the popups are not enabled by default for colortemplate files. 
I get it now why there was no explanation on how to enable them, they're expected to work by default! Hahahahah
