### ISSUE TITLE
Colors not recognized in Nvim

### ISSUE THREAD

**Issue by il-mich** [lifepillar/vim-colortemplate#45]
I installed the package with Plug in `.config/nvim/plugged`, and when I compile the default dark.colortemplate with `:Colortemplate! ~/.config/nvim` this comes up:

[colortemplate.txt](https://github.com/lifepillar/vim-colortemplate/files/5307114/colortemplate.txt)

It does not happen in Vim or GVim so it's Nvim specific

**Comment by lifepillar** [comment]
This is fixed in the current master.

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/pull/12377 was merged for optional function arguments on neovim nightly.
