### ISSUE TITLE
Wiki is wrong about installation without a plugin manager?

### ISSUE THREAD

**Issue by ProgMetalSlug** [lifepillar/vim-colortemplate#46]
The Wiki says, in the FAQs section:

> It's simple even without a plugin manager because vim-8+ provides package feature, see: :h package . Simply clone/download the repository and put it in ~/.vim/pack/vim-colortemplate

I think this is not quite right. To automatically load the plugin, the directory should be

    ~/.vim/pack/foo/start/vim-colortemplate

where `foo` could be any other name. To make the plugin optional instead, the directory should be

    ~/.vim/pack/foo/opt/vim-colortemplate

Then the plugin can be sourced by doing `:packadd vim-colortemplate`.

**Comment by lifepillar** [comment]
Good catch! I have updated the wiki page.

**Comment by ProgMetalSlug** [comment]
That works. Thanks!
