### ISSUE TITLE
Should not to change pwd to colortemplate dir

### ISSUE THREAD

**Issue by purefun** [lifepillar/vim-colortemplate#48]
reproduce:

1. :pwd -> ~/.config/nvim
2. open ~/.config/nvim/templates/theme.colortemplate
3. :Colortemplate!
4. :pwd -> ~/.config/nvim/templates

thx.

**Comment by lifepillar** [comment]
It should change the current directory only for the local buffer. Isn't that the case for you?

**Comment by purefun** [comment]
Thanks for your response. Telescope and LeaderF find files in the current directory, no matter what the current directory is relative to local buffer. IMHO, plugins should not change the cwd. BTW, `auxfile` is a wonderful feature. I use it for generating a lua file with color variables for galaxyline.

**Comment by lifepillar** [comment]
Ok, I have already marked this as a bug. I'll work on it.
