### ISSUE TITLE
Can't install with vim8's Packages

### ISSUE THREAD

**Issue by tuyenpm9** [lifepillar/vim-colortemplate#5]
I've just tried to install this plugin with vim8's native packages manager.  
Issued command:
`git submodule add git@github.com:lifepillar/vim-colortemplate pack/plugins/start/vim-colortemplate`  
And tried in vim `:Colortemplate .vim`, folder `.vim` existed and the command issued under home user. But gave me error: Not and editor command: Colortemplate  
I checked in `start` folder and `vim-colortemplate` existed along with all of its files/folders.

**Comment by lifepillar** [comment]
The `:Colortemplate` command is available only if the filetype is set to `colortemplate`. So, try `:set ft=colortemplate` first.
