### ISSUE TITLE
Vim(bdelete):E94:

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-colortemplate#51]
Reproduction steps:

- `:Colortemplate!`
- open generated colorscheme in same window
- `b #` back to template
- generate again, ok
- `b #` back to generated colorscheme, but it's now an unlisted buffer
- `b #` back to template
- `:Colortemplate!` fails with error E94

Is it really needed to delete the buffer? At least using `:bwipeout` this wouldn't happen.

**Comment by lifepillar** [comment]
Thanks for reporting, I can reproduce it. I always open the color scheme using the Source button in the toolbar, which opens a split window. Is that a suitable workaround for you?

I will look into it, but it will take some time (not much free time, currently). If you have any suggestion on how to fix it, you are welcome to submit a pull request.

**Comment by lifepillar** [comment]
Eventually, I have fixed this by removing the entire block checking for an existing buffer: I don't think that it breaks anything (for sure it doesn't break tests).
