### ISSUE TITLE
Variant: 0

### ISSUE THREAD

**Issue by romainl** [lifepillar/vim-colortemplate#53]
The lowest supported variant is currently `2` based on the assumption that `cterm*` are ignored in favor of `term` when `&t_Co <= 2`. This is wrong because `cterm*` are definitely used when `&t_Co == 2`:

<img width="697" alt="2c" src="https://user-images.githubusercontent.com/344335/138147918-15dd4ff3-6e65-4478-b4ed-6801c5d65052.png">

and ignored when `&t_Co < 2`:

<img width="697" alt="1c" src="https://user-images.githubusercontent.com/344335/138148272-beb12e40-99f0-4810-b390-74cbba982fc0.png">

Note that the behavior of `2` is generally the same as that of `8` except for these differences:

- when using color names, `red`/`darkred` and `blue`/`darkblue` are switched, as well as `yellow`/`darkyellow` and `cyan`/`darkcyan`: `ctermbg=darkred` gives you whatever the terminal emulator thinks is `darkblue` and so on,
- when using color indices, colors are in the standard "xterm" order: `1` is `darkred`, etc.

There is no difference between `1` and `0`.

**Comment by lifepillar** [comment]
This is addressed by the current master. Now, `Variant: 2` generates code that uses `cterm` attributes; `Variant: 1` and `Variant: 0` (now supported) generate code that uses `term` attributes.
