### ISSUE TITLE
cterm definitions for templates with dark and light backgrounds

### ISSUE THREAD

**Issue by habamax** [lifepillar/vim-colortemplate#54]
If template has definitions for both dark and light, dark has only gui definitions:

```

hi clear
let g:colors_name = 'habamax'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1

hi! link ErrorMsg Error
hi! link FoldColumn LineNr
hi! link LineNrAbove LineNr

..........

if &background ==# 'dark'
  let g:terminal_ansi_colors = ['#262626', '#d75f5f', '#87af87', '#afaf87', '#5f87af', '#af87af', '#5f8787', '#949494', '#626262', '#d7875f', '#afd7af', '#d7d787', '#87afd7', '#d7afd7', '#87afaf', '#bcbcbc']
  hi Normal guifg=#bcbcbc guibg=#262626 gui=NONE cterm=NONE
  hi Statusline guifg=#262626 guibg=#949494 gui=NONE cterm=NONE

  .............

  unlet s:t_Co
  finish
endif
```

**Comment by habamax** [comment]
Basically if I `set bg=light` then everything seems to work (switching t_Co and termguicolors is properly handled). For the dark it uses default cterm definitions.

**Comment by habamax** [comment]
@romainl fyi

**Comment by habamax** [comment]
Also (minor) links are defined for each block: 

* uncoditionally
* for 256
* for 16

**Comment by habamax** [comment]
Ignore the links, I should put them before any background definition and it would define them once.

**Comment by lifepillar** [comment]
Thanks for reporting. I have reverted the last commit in master and created a [dev branch](https://github.com/lifepillar/vim-colortemplate/tree/always-define-gui-colors) to address https://github.com/vim/colorschemes/issues/54.
