### ISSUE TITLE
Neovim error for option balloonexpr

### ISSUE THREAD

**Issue by rjurga** [lifepillar/vim-colortemplate#65]
I noticed an error happening with neovim, and it seems like [it's not the first time](https://github.com/lifepillar/vim-colortemplate/issues/41) that a similar one happens.

When I open a template file with neovim, upon loading vim-colortemplate I get the following errors:

```
Error detected while processing function <SNR>1_LoadFTPlugin:
line    2:
E518: Unknown option: balloonexpr<
```

It seems to work fine after that, except that there is no menu with the action buttons (Build, Show, etc) at the top of the neovim window. (unrelated?)

**Comment by lifepillar** [comment]
Thanks for reporting! Neovim has removed `balloonexpr`. The current master addresses that.

**Comment by lifepillar** [comment]
>there is no menu with the action buttons (Build, Show, etc) at the top of the neovim window.

Neovim does not have the window-toolbar feature (see `:help window-toolbar` in Vim).

**Comment by rjurga** [comment]
Thank you. Tested and no error anymore!
