### ISSUE TITLE
Not working inside neovim

### ISSUE THREAD

**Issue by kristijanhusak** [lifepillar/vim-colortemplate#7]
Hi, 

I wanted to add highlighting to templates for this issue https://github.com/lifepillar/vim-solarized8/issues/42#issuecomment-387011244 , and when i came to the part where i need to rebuild colorscheme by colortemplate, i got an error in the middle of the building:

```
[Colortemplate] Vim(return):E117: Unknown function: isnan
```

Then i tried to find `isnan` in help, and really the function doesn't exist.

My neovim version: NVIM v0.3.0-dev

**Comment by lifepillar** [comment]
Mmh, `isnan()` has been introduced with patch 7.4.1407. Maybe, NeoVim hasn't picked it. Thanks for reporting, I'll see whether I can find a workaround.

**Comment by lifepillar** [comment]
You should be able to use Colortemplate in NeoVim now. Feel free to re-open, or open a new issue, if necessary.

**Comment by janlazo** [comment]
Neovim has `isnan` now so the check can be changed to `exists('*isnan')`.

**Comment by lifepillar** [comment]
Thanks for pointing that out!
