### ISSUE TITLE
gitignore tags file?

### ISSUE THREAD

**Issue by johnridesabike** [lifepillar/vim-colortemplate#71]
I have this plugin installed with git. Whenever I generate helptags (i.e. `:helptags ALL`), Vim will modify this plugin's existing `doc/tags` file, which then creates a dirty git status. It's not a huge problem, but it's annoying to deal with.

I think most Vim plugins have their tags files ignored with `.gitignore`, so I'm wondering if that would be a good idea here as well. 

<details><summary>git diff output</summary>

```diff
@@ -42,8 +42,6 @@ colortemplate-toolbar	colortemplate.txt	/*colortemplate-toolbar*
 colortemplate-variants	colortemplate.txt	/*colortemplate-variants*
 colortemplate-verbatim	colortemplate.txt	/*colortemplate-verbatim*
 colortemplate.txt	colortemplate.txt	/*colortemplate.txt*
-dark.txt	dark.txt	/*dark.txt*
-dark_and_light.txt	dark_and_light.txt	/*dark_and_light.txt*
 ft-colortemplate	colortemplate.txt	/*ft-colortemplate*
 g:@shortname_transp_bg	colortemplate.txt	/*g:@shortname_transp_bg*
 g:colortemplate_backward_compatible	colortemplate.txt	/*g:colortemplate_backward_compatible*
@@ -76,7 +74,3 @@ g:colortemplate_toolbar_actions	colortemplate.txt	/*g:colortemplate_toolbar_acti
 g:colortemplate_toolbar_items	colortemplate.txt	/*g:colortemplate_toolbar_items*
 g:colortemplate_use_tabs	colortemplate.txt	/*g:colortemplate_use_tabs*
 g:colortemplate_warnings	colortemplate.txt	/*g:colortemplate_warnings*
-g:dark_and_light_transp_bg	dark_and_light.txt	/*g:dark_and_light_transp_bg*
-g:dark_transp_bg	dark.txt	/*g:dark_transp_bg*
-g:light_transp_bg	light.txt	/*g:light_transp_bg*
-light.txt	light.txt	/*light.txt*

```

</details>

**Comment by lifepillar** [comment]
Ignoring `tags` is certainly possible. I am wondering, though, why regenerating it with `helptags` produces a different result than in the repo. I'll double-check whether it is up to date.

**Comment by lifepillar** [comment]
Ah, good catch: there were some ignored files in my local `doc` folder. The issue should be fixed. Can you try with the current master?

**Comment by johnridesabike** [comment]
The current master seem good! Running `helptags` does not dirty this repo's status.

**Comment by lifepillar** [comment]
Closing this, then. I prefer to leave the `tags` file, because that makes the help items discoverable without the user having to run `helptags` before.
