### ISSUE TITLE
The `Check` interface seems to disallow scrolling down (v3)

### ISSUE THREAD

**Issue by riskygit** [lifepillar/vim-colortemplate#82]
After running `:ColortemplateCheck`, the interface indicates the presence of additional lines with `-- More --`, but pressing `j` or using an arrow key presents `Press a key to continue`. After pressing a key, `Check` exits back to the editor. `Shift-j` reveals keys that should scroll, but it appears you can only scroll up... but it doesn't scroll the list; it just moves the whole `Check` interface (I think).

**Comment by lifepillar** [comment]
`:ColortemplateCheck` is just an alias for `:runtime colors/tools/check_colors.vim`, which is a script embedded with Vim. The scrolling behaviour should just be default Vim's behaviour. Anyway, the script is part of the [vim/colorschemes](https://github.com/vim/colorschemes) repo, so you may want to ask there.

**Comment by riskygit** [comment]
Right; this isn't really important anyway. Just something I noticed.
