### ISSUE TITLE
format of Last Updated

### ISSUE THREAD

**Issue by habamax** [lifepillar/vim-colortemplate#84]
Hi, vim project requires `Last Updated` format to be `%Y %b %d`, is it possible either add an option or change it? Currently it is `%c` which is OS dependent.

```
  if s:getopt('timestamp')
    call s:put(a:bufnr,         '" Last Updated: ' . strftime("%c"))
  endif
```

relates https://github.com/vim/vim/pull/15423

@chrisbra, is it ok to have time in `Last Updated`?

**Comment by chrisbra** [comment]
It's not a hard requirements, but in general we prefer to have a consistent "Last Change: " date format header.

**Comment by lifepillar** [comment]
That's fine. Any preference between `Last Updated:` and `Last Change:`?

**Comment by chrisbra** [comment]
`Last Updated` seems to be mostly coming from the color schemes ;).
Also:
```
chrisbra@host:~/code/vim/runtime (master)$ git grep 'Last Updated:' |wc -l
42
chrisbra@host:~/code/vim/runtime (master)$ git grep 'Last Change:' |wc -l
1153
chrisbra@host:~/code/vim/runtime (master)$
```
quite obvious I think :)

**Comment by lifepillar** [comment]
Fixed in master. Thanks for your feedback!
