### ISSUE TITLE
Fallback to 16 colors without option

### ISSUE THREAD

**Issue by caksoylar** [lifepillar/vim-colortemplate#9]
Is there a way to allow falling back to 16 colors if `16 <= &t_Co < 256` but keeping the default 256 fallback if `t_Co == 256`? Right now I can set `Terminal Colors: 256,16` which fails with 16 colors if `@optionprefix_use16 = 1` is not set and forces 16 colors otherwise.

Also, thank you for developing this tool. It's great for creating well-behaving colorschemes by default and is much easier than creating a colorscheme script from scratch.

**Comment by lifepillar** [comment]
Mmh, no, it is not possible. Currently, the user has to put

```vim
let g:somecolorscheme_use16 = (&t_Co < 256)
```

in a `vimrc`. The kind of automatic fallback you suggest may result in completely wrong colors being displayed, which might surprise the user. Do you think it is worth anyway? Are there examples of colorschemes that do it that way?

**Comment by caksoylar** [comment]
I think that if the author specifies Base16 colors in the palette and also `Terminal Colors: 256,16`, in the template, it is reasonable to assume that falling back to 16 colors will be correctly handled by the colorscheme. Are you thinking about cases where `t_Co` may be misconfigured? E.g. the terminal supports 256 even though the option is set to 16.

Not many colorschemes support 256 which makes sense, but I found [romainl's Apprentice](https://github.com/romainl/Apprentice/blob/master/colors/apprentice.vim#L129) does.

FWIW, I was hoping to have basic 16 color support for my own use cases, where I sometimes work with Windows terminal and wanted to avoid an additional check in my vimrc.

**Comment by lifepillar** [comment]
Please test the current master, which implements automatic fallback to a 16-color palette when `t_Co` is less than 256 and the user has not explicitly set `@optionprefix_use16`.

 Feel free to re-open if it doesn't work as expected.

**Comment by caksoylar** [comment]
Thanks, I pulled the new master branch and regenerated the colorscheme. While I don't get the error message with a 16 color terminal anymore, it also still seems to use 256 colors.

This is the diff I get:

    diff --git a/vim/colors/mystical_tutor.vim b/vim/colors/mystical_tutor.vim
    index f23f666..7d15bcc 100644
    --- a/vim/colors/mystical_tutor.vim
    +++ b/vim/colors/mystical_tutor.vim
    @@ -3,10 +3,10 @@
     " Author:       Myself <myself@somewhere.org>
     " Maintainer:   Myself <myself@somewhere.org>
     " License:      Vim License (see `:help license`)
    -" Last Updated: Tue 19 Jun 2018 01:10:16 PM DST
    +" Last Updated: Wed 20 Jun 2018 10:26:01 AM DST
     
     if !(has('termguicolors') && &termguicolors) && !has('gui_running')
    -      \ && (!exists('&t_Co') || &t_Co < (get(g:, 'mystical_tutor_use16', 0) ? 16 : 256))
    +      \ && (!exists('&t_Co') || &t_Co < (get(g:, 'mystical_tutor_use16', &t_Co < 256) ? 16 : 256))
       echoerr '[Mystical Tutor] There are not enough colors.'
       finish
     endif

The color definitions part of the file is the same (abridged below):

    if !get(g:, 'mystical_tutor_use16', 0)
      " 256 color definitions
      finish
    endif

    " 16-color variant
    if !has('gui_running') && get(g:, 'mystical_tutor_transp_bg', 0)
      hi Normal ctermfg=LightGray ctermbg=NONE guifg=#d9d9d9 guibg=NONE guisp=NONE cterm=NONE gui=NONE
      hi Terminal ctermfg=LightGray ctermbg=NONE guifg=#d9d9d9 guibg=NONE guisp=NONE cterm=NONE gui=NONE
    else
      hi Normal ctermfg=LightGray ctermbg=Black guifg=#d9d9d9 guibg=#1e2227 guisp=NONE cterm=NONE gui=NONE
      hi Terminal ctermfg=LightGray ctermbg=Black guifg=#d9d9d9 guibg=#1e2227 guisp=NONE cterm=NONE gui=NONE
    endif
    " 16 color definitions
    finish

Notably, the first line above didn't change so that's why I think it is not falling back to 16. Is this the behavior you were expecting?

**Comment by lifepillar** [comment]
That should be fixed in the current master.

**Comment by caksoylar** [comment]
That did it, thanks! 👍
